### PR TITLE
Updated prefix to make it compatible with angular 1.3

### PR DESCRIPTION
**Pull request by nanorepublica**
In angular 1.3 html5Mode is now an object so a boolean check always returns the same result, I have done a check using the provided type function to decide whether to inspect the 'enabled' property on the object (1.3) or just check the boolean (1.2)

### CODE REVIEW

**Comment by eilinora** [comment]
Can you please accept this request? It is preventing the use of using this great library with v1.3 without manual updates. 

Thanks!

**Comment by rafaheringer** [comment]
Please accept this request.

**Comment by airtonix** [comment]
@nanorepublica Needs to be updated with supporting tests please.

**Comment by airtonix** [comment]
Implemented in recent update.

**Pull request closed without merging**
